/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const TradeOrder = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'coinSymbol' : IDL.Text,
  'coinQuantity' : IDL.Float64,
  'orderType' : OrderType,
  'priceAtExecution' : IDL.Float64,
  'timestamp' : IDL.Int,
  'fiatAmount' : IDL.Float64,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'coinId' : IDL.Text,
});
export const ChartKind = IDL.Variant({
  'line' : IDL.Null,
  'candle' : IDL.Null,
});
export const LinePoint = IDL.Record({
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const ChartData = IDL.Record({
  'days' : IDL.Nat,
  'kind' : ChartKind,
  'line' : IDL.Vec(LinePoint),
  'candles' : IDL.Vec(Candle),
  'updatedAt' : IDL.Int,
  'coinId' : IDL.Text,
});
export const ApiResult_3 = IDL.Variant({ 'ok' : ChartData, 'err' : IDL.Text });
export const NewsItem = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'publishedAt' : IDL.Int,
});
export const ApiResult_2 = IDL.Variant({
  'ok' : IDL.Vec(NewsItem),
  'err' : IDL.Text,
});
export const GlobalStats = IDL.Record({
  'btcDominance' : IDL.Float64,
  'totalMarketCap' : IDL.Float64,
  'activeCryptocurrencies' : IDL.Nat,
  'marketCapChangePercentage24h' : IDL.Float64,
  'totalVolume24h' : IDL.Float64,
  'markets' : IDL.Nat,
  'ethDominance' : IDL.Float64,
});
export const GlobalResponse = IDL.Record({
  'updatedAt' : IDL.Int,
  'stats' : GlobalStats,
});
export const ApiResult_1 = IDL.Variant({
  'ok' : GlobalResponse,
  'err' : IDL.Text,
});
export const SparklineData = IDL.Vec(IDL.Float64);
export const Coin = IDL.Record({
  'id' : IDL.Text,
  'ath' : IDL.Float64,
  'athChangePercentage' : IDL.Float64,
  'currentPrice' : IDL.Float64,
  'totalVolume' : IDL.Float64,
  'circulatingSupply' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'priceChangePercentage24h' : IDL.Float64,
  'priceChangePercentage1h' : IDL.Float64,
  'priceChangePercentage7d' : IDL.Float64,
  'low24h' : IDL.Float64,
  'totalSupply' : IDL.Float64,
  'high24h' : IDL.Float64,
  'sparkline7d' : SparklineData,
  'image' : IDL.Text,
  'marketCapRank' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const MarketResponse = IDL.Record({
  'page' : IDL.Nat,
  'coins' : IDL.Vec(Coin),
  'perPage' : IDL.Nat,
  'updatedAt' : IDL.Int,
});
export const ApiResult = IDL.Variant({
  'ok' : MarketResponse,
  'err' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'coinSymbol' : IDL.Text,
  'pricePerCoin' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'coinName' : IDL.Text,
  'coinId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const PriceAlert = IDL.Record({
  'id' : IDL.Text,
  'direction' : IDL.Variant({ 'above' : IDL.Null, 'below' : IDL.Null }),
  'createdAt' : IDL.Int,
  'targetPrice' : IDL.Float64,
  'coinName' : IDL.Text,
  'coinId' : IDL.Text,
  'triggered' : IDL.Bool,
});
export const UserId = IDL.Principal;
export const ReportPrefs = IDL.Record({
  'roundingDecimals' : IDL.Nat,
  'defaultChartDays' : IDL.Nat,
});
export const UserSettings = IDL.Record({
  'theme' : IDL.Text,
  'colorblind' : IDL.Bool,
  'language' : IDL.Text,
  'reportPrefs' : ReportPrefs,
  'currency' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'settings' : IDL.Opt(UserSettings),
  'profilePictureUrl' : IDL.Opt(IDL.Text),
});
export const TransactionInput = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'coinSymbol' : IDL.Text,
  'pricePerCoin' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'coinName' : IDL.Text,
  'coinId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const ReportPrefsInput = IDL.Record({
  'roundingDecimals' : IDL.Nat,
  'defaultChartDays' : IDL.Nat,
});
export const ProfileInput = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'profilePictureUrl' : IDL.Opt(IDL.Text),
});
export const SettingsInput = IDL.Record({
  'theme' : IDL.Text,
  'colorblind' : IDL.Bool,
  'language' : IDL.Text,
  'currency' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTradeOrder' : IDL.Func([TradeOrder], [], []),
  'cancelTradeOrder' : IDL.Func([IDL.Text], [], []),
  'completeTradeOrder' : IDL.Func([IDL.Text], [], []),
  'deletePriceAlert' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getCoinChart' : IDL.Func([IDL.Text, IDL.Nat, ChartKind], [ApiResult_3], []),
  'getCoinNews' : IDL.Func([IDL.Text], [ApiResult_2], []),
  'getGlobalStats' : IDL.Func([], [ApiResult_1], []),
  'getMarketData' : IDL.Func([], [ApiResult], []),
  'getMarketDataPage' : IDL.Func([IDL.Nat, IDL.Nat], [ApiResult], []),
  'getPortfolioTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getPriceAlerts' : IDL.Func([], [IDL.Vec(PriceAlert)], ['query']),
  'getTradeOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
  'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'setPortfolioTransactions' : IDL.Func([IDL.Vec(TransactionInput)], [], []),
  'setPriceAlert' : IDL.Func(
      [PriceAlert],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setWatchlist' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePriceAlert' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateReportPrefs' : IDL.Func([ReportPrefsInput], [UserSettings], []),
  'updateUserProfile' : IDL.Func([ProfileInput], [UserProfile], []),
  'updateUserSettings' : IDL.Func([SettingsInput], [UserSettings], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const TradeOrder = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'coinSymbol' : IDL.Text,
    'coinQuantity' : IDL.Float64,
    'orderType' : OrderType,
    'priceAtExecution' : IDL.Float64,
    'timestamp' : IDL.Int,
    'fiatAmount' : IDL.Float64,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'coinId' : IDL.Text,
  });
  const ChartKind = IDL.Variant({ 'line' : IDL.Null, 'candle' : IDL.Null });
  const LinePoint = IDL.Record({
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const ChartData = IDL.Record({
    'days' : IDL.Nat,
    'kind' : ChartKind,
    'line' : IDL.Vec(LinePoint),
    'candles' : IDL.Vec(Candle),
    'updatedAt' : IDL.Int,
    'coinId' : IDL.Text,
  });
  const ApiResult_3 = IDL.Variant({ 'ok' : ChartData, 'err' : IDL.Text });
  const NewsItem = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'publishedAt' : IDL.Int,
  });
  const ApiResult_2 = IDL.Variant({
    'ok' : IDL.Vec(NewsItem),
    'err' : IDL.Text,
  });
  const GlobalStats = IDL.Record({
    'btcDominance' : IDL.Float64,
    'totalMarketCap' : IDL.Float64,
    'activeCryptocurrencies' : IDL.Nat,
    'marketCapChangePercentage24h' : IDL.Float64,
    'totalVolume24h' : IDL.Float64,
    'markets' : IDL.Nat,
    'ethDominance' : IDL.Float64,
  });
  const GlobalResponse = IDL.Record({
    'updatedAt' : IDL.Int,
    'stats' : GlobalStats,
  });
  const ApiResult_1 = IDL.Variant({ 'ok' : GlobalResponse, 'err' : IDL.Text });
  const SparklineData = IDL.Vec(IDL.Float64);
  const Coin = IDL.Record({
    'id' : IDL.Text,
    'ath' : IDL.Float64,
    'athChangePercentage' : IDL.Float64,
    'currentPrice' : IDL.Float64,
    'totalVolume' : IDL.Float64,
    'circulatingSupply' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'priceChangePercentage24h' : IDL.Float64,
    'priceChangePercentage1h' : IDL.Float64,
    'priceChangePercentage7d' : IDL.Float64,
    'low24h' : IDL.Float64,
    'totalSupply' : IDL.Float64,
    'high24h' : IDL.Float64,
    'sparkline7d' : SparklineData,
    'image' : IDL.Text,
    'marketCapRank' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const MarketResponse = IDL.Record({
    'page' : IDL.Nat,
    'coins' : IDL.Vec(Coin),
    'perPage' : IDL.Nat,
    'updatedAt' : IDL.Int,
  });
  const ApiResult = IDL.Variant({ 'ok' : MarketResponse, 'err' : IDL.Text });
  const TransactionType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Timestamp = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'coinSymbol' : IDL.Text,
    'pricePerCoin' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'coinName' : IDL.Text,
    'coinId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const PriceAlert = IDL.Record({
    'id' : IDL.Text,
    'direction' : IDL.Variant({ 'above' : IDL.Null, 'below' : IDL.Null }),
    'createdAt' : IDL.Int,
    'targetPrice' : IDL.Float64,
    'coinName' : IDL.Text,
    'coinId' : IDL.Text,
    'triggered' : IDL.Bool,
  });
  const UserId = IDL.Principal;
  const ReportPrefs = IDL.Record({
    'roundingDecimals' : IDL.Nat,
    'defaultChartDays' : IDL.Nat,
  });
  const UserSettings = IDL.Record({
    'theme' : IDL.Text,
    'colorblind' : IDL.Bool,
    'language' : IDL.Text,
    'reportPrefs' : ReportPrefs,
    'currency' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'settings' : IDL.Opt(UserSettings),
    'profilePictureUrl' : IDL.Opt(IDL.Text),
  });
  const TransactionInput = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'coinSymbol' : IDL.Text,
    'pricePerCoin' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'coinName' : IDL.Text,
    'coinId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ReportPrefsInput = IDL.Record({
    'roundingDecimals' : IDL.Nat,
    'defaultChartDays' : IDL.Nat,
  });
  const ProfileInput = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'profilePictureUrl' : IDL.Opt(IDL.Text),
  });
  const SettingsInput = IDL.Record({
    'theme' : IDL.Text,
    'colorblind' : IDL.Bool,
    'language' : IDL.Text,
    'currency' : IDL.Text,
  });
  
  return IDL.Service({
    'addTradeOrder' : IDL.Func([TradeOrder], [], []),
    'cancelTradeOrder' : IDL.Func([IDL.Text], [], []),
    'completeTradeOrder' : IDL.Func([IDL.Text], [], []),
    'deletePriceAlert' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getCoinChart' : IDL.Func(
        [IDL.Text, IDL.Nat, ChartKind],
        [ApiResult_3],
        [],
      ),
    'getCoinNews' : IDL.Func([IDL.Text], [ApiResult_2], []),
    'getGlobalStats' : IDL.Func([], [ApiResult_1], []),
    'getMarketData' : IDL.Func([], [ApiResult], []),
    'getMarketDataPage' : IDL.Func([IDL.Nat, IDL.Nat], [ApiResult], []),
    'getPortfolioTransactions' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getPriceAlerts' : IDL.Func([], [IDL.Vec(PriceAlert)], ['query']),
    'getTradeOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getUserSettings' : IDL.Func([], [IDL.Opt(UserSettings)], ['query']),
    'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'setPortfolioTransactions' : IDL.Func([IDL.Vec(TransactionInput)], [], []),
    'setPriceAlert' : IDL.Func(
        [PriceAlert],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setWatchlist' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePriceAlert' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateReportPrefs' : IDL.Func([ReportPrefsInput], [UserSettings], []),
    'updateUserProfile' : IDL.Func([ProfileInput], [UserProfile], []),
    'updateUserSettings' : IDL.Func([SettingsInput], [UserSettings], []),
  });
};

export const init = ({ IDL }) => { return []; };