/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApiResult = { 'ok' : MarketResponse } |
  { 'err' : string };
export type ApiResult_1 = { 'ok' : GlobalResponse } |
  { 'err' : string };
export type ApiResult_2 = { 'ok' : Array<NewsItem> } |
  { 'err' : string };
export type ApiResult_3 = { 'ok' : ChartData } |
  { 'err' : string };
export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'timestamp' : bigint,
}
export interface ChartData {
  'days' : bigint,
  'kind' : ChartKind,
  'line' : Array<LinePoint>,
  'candles' : Array<Candle>,
  'updatedAt' : bigint,
  'coinId' : string,
}
export type ChartKind = { 'line' : null } |
  { 'candle' : null };
export interface Coin {
  'id' : string,
  'ath' : number,
  'athChangePercentage' : number,
  'currentPrice' : number,
  'totalVolume' : number,
  'circulatingSupply' : number,
  'marketCap' : number,
  'name' : string,
  'priceChangePercentage24h' : number,
  'priceChangePercentage1h' : number,
  'priceChangePercentage7d' : number,
  'low24h' : number,
  'totalSupply' : number,
  'high24h' : number,
  'sparkline7d' : SparklineData,
  'image' : string,
  'marketCapRank' : bigint,
  'symbol' : string,
}
export interface GlobalResponse { 'updatedAt' : bigint, 'stats' : GlobalStats }
export interface GlobalStats {
  'btcDominance' : number,
  'totalMarketCap' : number,
  'activeCryptocurrencies' : bigint,
  'marketCapChangePercentage24h' : number,
  'totalVolume24h' : number,
  'markets' : bigint,
  'ethDominance' : number,
}
export interface LinePoint { 'timestamp' : bigint, 'price' : number }
export interface MarketResponse {
  'page' : bigint,
  'coins' : Array<Coin>,
  'perPage' : bigint,
  'updatedAt' : bigint,
}
export interface NewsItem {
  'url' : string,
  'title' : string,
  'source' : string,
  'publishedAt' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type OrderType = { 'buy' : null } |
  { 'sell' : null };
export interface PriceAlert {
  'id' : string,
  'direction' : { 'above' : null } |
    { 'below' : null },
  'createdAt' : bigint,
  'targetPrice' : number,
  'coinName' : string,
  'coinId' : string,
  'triggered' : boolean,
}
export interface ProfileInput {
  'username' : string,
  'displayName' : string,
  'profilePictureUrl' : [] | [string],
}
export interface ReportPrefs {
  'roundingDecimals' : bigint,
  'defaultChartDays' : bigint,
}
export interface ReportPrefsInput {
  'roundingDecimals' : bigint,
  'defaultChartDays' : bigint,
}
export interface SettingsInput {
  'theme' : string,
  'colorblind' : boolean,
  'language' : string,
  'currency' : string,
}
export type SparklineData = Array<number>;
export type Timestamp = bigint;
export interface TradeOrder {
  'id' : string,
  'status' : OrderStatus,
  'coinSymbol' : string,
  'coinQuantity' : number,
  'orderType' : OrderType,
  'priceAtExecution' : number,
  'timestamp' : bigint,
  'fiatAmount' : number,
  'stripePaymentIntentId' : [] | [string],
  'coinId' : string,
}
export interface Transaction {
  'id' : string,
  'transactionType' : TransactionType,
  'coinSymbol' : string,
  'pricePerCoin' : number,
  'notes' : [] | [string],
  'timestamp' : Timestamp,
  'coinName' : string,
  'coinId' : string,
  'amount' : number,
}
export interface TransactionInput {
  'id' : string,
  'transactionType' : TransactionType,
  'coinSymbol' : string,
  'pricePerCoin' : number,
  'notes' : [] | [string],
  'timestamp' : Timestamp,
  'coinName' : string,
  'coinId' : string,
  'amount' : number,
}
export type TransactionType = { 'buy' : null } |
  { 'sell' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'username' : string,
  'displayName' : string,
  'createdAt' : Timestamp,
  'settings' : [] | [UserSettings],
  'profilePictureUrl' : [] | [string],
}
export interface UserSettings {
  'theme' : string,
  'colorblind' : boolean,
  'language' : string,
  'reportPrefs' : ReportPrefs,
  'currency' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addTradeOrder' : ActorMethod<[TradeOrder], undefined>,
  'cancelTradeOrder' : ActorMethod<[string], undefined>,
  'completeTradeOrder' : ActorMethod<[string], undefined>,
  'deletePriceAlert' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getCoinChart' : ActorMethod<[string, bigint, ChartKind], ApiResult_3>,
  'getCoinNews' : ActorMethod<[string], ApiResult_2>,
  'getGlobalStats' : ActorMethod<[], ApiResult_1>,
  'getMarketData' : ActorMethod<[], ApiResult>,
  'getMarketDataPage' : ActorMethod<[bigint, bigint], ApiResult>,
  'getPortfolioTransactions' : ActorMethod<[], Array<Transaction>>,
  'getPriceAlerts' : ActorMethod<[], Array<PriceAlert>>,
  'getTradeOrders' : ActorMethod<[], Array<TradeOrder>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserSettings' : ActorMethod<[], [] | [UserSettings]>,
  'getWatchlist' : ActorMethod<[], Array<string>>,
  'setPortfolioTransactions' : ActorMethod<
    [Array<TransactionInput>],
    undefined
  >,
  'setPriceAlert' : ActorMethod<
    [PriceAlert],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setWatchlist' : ActorMethod<[Array<string>], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePriceAlert' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateReportPrefs' : ActorMethod<[ReportPrefsInput], UserSettings>,
  'updateUserProfile' : ActorMethod<[ProfileInput], UserProfile>,
  'updateUserSettings' : ActorMethod<[SettingsInput], UserSettings>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];