/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ReportPrefsInput {
    roundingDecimals: bigint;
    defaultChartDays: bigint;
}
export type ApiResult_1 = {
    __kind__: "ok";
    ok: GlobalResponse;
} | {
    __kind__: "err";
    err: string;
};
export interface NewsItem {
    url: string;
    title: string;
    source: string;
    publishedAt: bigint;
}
export interface Transaction {
    id: string;
    transactionType: TransactionType;
    coinSymbol: string;
    pricePerCoin: number;
    notes?: string;
    timestamp: Timestamp;
    coinName: string;
    coinId: string;
    amount: number;
}
export interface MarketResponse {
    page: bigint;
    coins: Array<Coin>;
    perPage: bigint;
    updatedAt: bigint;
}
export interface TradeOrder {
    id: string;
    status: OrderStatus;
    coinSymbol: string;
    coinQuantity: number;
    orderType: OrderType;
    priceAtExecution: number;
    timestamp: bigint;
    fiatAmount: number;
    stripePaymentIntentId?: string;
    coinId: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Candle {
    low: number;
    high: number;
    close: number;
    open: number;
    timestamp: bigint;
}
export interface SettingsInput {
    theme: string;
    colorblind: boolean;
    language: string;
    currency: string;
}
export interface ChartData {
    days: bigint;
    kind: ChartKind;
    line: Array<LinePoint>;
    candles: Array<Candle>;
    updatedAt: bigint;
    coinId: string;
}
export interface GlobalStats {
    btcDominance: number;
    totalMarketCap: number;
    activeCryptocurrencies: bigint;
    marketCapChangePercentage24h: number;
    totalVolume24h: number;
    markets: bigint;
    ethDominance: number;
}
export interface TransactionInput {
    id: string;
    transactionType: TransactionType;
    coinSymbol: string;
    pricePerCoin: number;
    notes?: string;
    timestamp: Timestamp;
    coinName: string;
    coinId: string;
    amount: number;
}
export interface LinePoint {
    timestamp: bigint;
    price: number;
}
export interface Coin {
    id: string;
    ath: number;
    athChangePercentage: number;
    currentPrice: number;
    totalVolume: number;
    circulatingSupply: number;
    marketCap: number;
    name: string;
    priceChangePercentage24h: number;
    priceChangePercentage1h: number;
    priceChangePercentage7d: number;
    low24h: number;
    totalSupply: number;
    high24h: number;
    sparkline7d: SparklineData;
    image: string;
    marketCapRank: bigint;
    symbol: string;
}
export type ApiResult_3 = {
    __kind__: "ok";
    ok: ChartData;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult = {
    __kind__: "ok";
    ok: MarketResponse;
} | {
    __kind__: "err";
    err: string;
};
export type ApiResult_2 = {
    __kind__: "ok";
    ok: Array<NewsItem>;
} | {
    __kind__: "err";
    err: string;
};
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface GlobalResponse {
    updatedAt: bigint;
    stats: GlobalStats;
}
export type UserId = Principal;
export interface PriceAlert {
    id: string;
    direction: Variant_above_below;
    createdAt: bigint;
    targetPrice: number;
    coinName: string;
    coinId: string;
    triggered: boolean;
}
export interface UserSettings {
    theme: string;
    colorblind: boolean;
    language: string;
    reportPrefs: ReportPrefs;
    currency: string;
}
export type SparklineData = Array<number>;
export interface ProfileInput {
    username: string;
    displayName: string;
    profilePictureUrl?: string;
}
export interface UserProfile {
    id: UserId;
    username: string;
    displayName: string;
    createdAt: Timestamp;
    settings?: UserSettings;
    profilePictureUrl?: string;
}
export interface ReportPrefs {
    roundingDecimals: bigint;
    defaultChartDays: bigint;
}
export enum ChartKind {
    line = "line",
    candle = "candle"
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum OrderType {
    buy = "buy",
    sell = "sell"
}
export enum Variant_above_below {
    above = "above",
    below = "below"
}
export interface backendInterface {
    addTradeOrder(order: TradeOrder): Promise<void>;
    cancelTradeOrder(orderId: string): Promise<void>;
    completeTradeOrder(orderId: string): Promise<void>;
    deletePriceAlert(alertId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCoinChart(coinId: string, days: bigint, kind: ChartKind): Promise<ApiResult_3>;
    getCoinNews(coinId: string): Promise<ApiResult_2>;
    getGlobalStats(): Promise<ApiResult_1>;
    getMarketData(): Promise<ApiResult>;
    getMarketDataPage(page: bigint, perPage: bigint): Promise<ApiResult>;
    getPortfolioTransactions(): Promise<Array<Transaction>>;
    getPriceAlerts(): Promise<Array<PriceAlert>>;
    getTradeOrders(): Promise<Array<TradeOrder>>;
    getUserProfile(): Promise<UserProfile | null>;
    getUserSettings(): Promise<UserSettings | null>;
    getWatchlist(): Promise<Array<string>>;
    setPortfolioTransactions(txs: Array<TransactionInput>): Promise<void>;
    setPriceAlert(alert: PriceAlert): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setWatchlist(coinIds: Array<string>): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePriceAlert(alertId: string, triggered: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateReportPrefs(input: ReportPrefsInput): Promise<UserSettings>;
    updateUserProfile(input: ProfileInput): Promise<UserProfile>;
    updateUserSettings(input: SettingsInput): Promise<UserSettings>;
}
import type { ApiResult as _ApiResult, ApiResult_1 as _ApiResult_1, ApiResult_2 as _ApiResult_2, ApiResult_3 as _ApiResult_3, Candle as _Candle, ChartData as _ChartData, ChartKind as _ChartKind, GlobalResponse as _GlobalResponse, LinePoint as _LinePoint, MarketResponse as _MarketResponse, NewsItem as _NewsItem, OrderStatus as _OrderStatus, OrderType as _OrderType, PriceAlert as _PriceAlert, ProfileInput as _ProfileInput, Timestamp as _Timestamp, TradeOrder as _TradeOrder, Transaction as _Transaction, TransactionInput as _TransactionInput, TransactionType as _TransactionType, UserId as _UserId, UserProfile as _UserProfile, UserSettings as _UserSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTradeOrder(arg0: TradeOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTradeOrder(to_candid_TradeOrder_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTradeOrder(to_candid_TradeOrder_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async cancelTradeOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTradeOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTradeOrder(arg0);
            return result;
        }
    }
    async completeTradeOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTradeOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTradeOrder(arg0);
            return result;
        }
    }
    async deletePriceAlert(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePriceAlert(arg0);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePriceAlert(arg0);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoinChart(arg0: string, arg1: bigint, arg2: ChartKind): Promise<ApiResult_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinChart(arg0, arg1, to_candid_ChartKind_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_ApiResult_3_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinChart(arg0, arg1, to_candid_ChartKind_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_ApiResult_3_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoinNews(arg0: string): Promise<ApiResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinNews(arg0);
                return from_candid_ApiResult_2_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinNews(arg0);
            return from_candid_ApiResult_2_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalStats(): Promise<ApiResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalStats();
                return from_candid_ApiResult_1_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalStats();
            return from_candid_ApiResult_1_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketData(): Promise<ApiResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketData();
                return from_candid_ApiResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketData();
            return from_candid_ApiResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketDataPage(arg0: bigint, arg1: bigint): Promise<ApiResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketDataPage(arg0, arg1);
                return from_candid_ApiResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketDataPage(arg0, arg1);
            return from_candid_ApiResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioTransactions();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioTransactions();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceAlerts(): Promise<Array<PriceAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceAlerts();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceAlerts();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeOrders(): Promise<Array<TradeOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeOrders();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeOrders();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSettings(): Promise<UserSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSettings();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSettings();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchlist(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async setPortfolioTransactions(arg0: Array<TransactionInput>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPortfolioTransactions(to_candid_vec_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPortfolioTransactions(to_candid_vec_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPriceAlert(arg0: PriceAlert): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setPriceAlert(to_candid_PriceAlert_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPriceAlert(to_candid_PriceAlert_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async setWatchlist(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWatchlist(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePriceAlert(arg0: string, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePriceAlert(arg0, arg1);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePriceAlert(arg0, arg1);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateReportPrefs(arg0: ReportPrefsInput): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportPrefs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportPrefs(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: ProfileInput): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_ProfileInput_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_ProfileInput_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserSettings(arg0: SettingsInput): Promise<UserSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserSettings(arg0);
            return result;
        }
    }
}
function from_candid_ApiResult_1_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_1): ApiResult_1 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_2_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_2): ApiResult_2 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_3_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult_3): ApiResult_3 {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ApiResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiResult): ApiResult {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ChartData_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartData): ChartData {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ChartKind_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChartKind): ChartKind {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PriceAlert_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceAlert): PriceAlert {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TradeOrder_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeOrder): TradeOrder {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSettings]): UserSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    days: bigint;
    kind: _ChartKind;
    line: Array<_LinePoint>;
    candles: Array<_Candle>;
    updatedAt: bigint;
    coinId: string;
}): {
    days: bigint;
    kind: ChartKind;
    line: Array<LinePoint>;
    candles: Array<Candle>;
    updatedAt: bigint;
    coinId: string;
} {
    return {
        days: value.days,
        kind: from_candid_ChartKind_n14(_uploadFile, _downloadFile, value.kind),
        line: value.line,
        candles: value.candles,
        updatedAt: value.updatedAt,
        coinId: value.coinId
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionType: _TransactionType;
    coinSymbol: string;
    pricePerCoin: number;
    notes: [] | [string];
    timestamp: _Timestamp;
    coinName: string;
    coinId: string;
    amount: number;
}): {
    id: string;
    transactionType: TransactionType;
    coinSymbol: string;
    pricePerCoin: number;
    notes?: string;
    timestamp: Timestamp;
    coinName: string;
    coinId: string;
    amount: number;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n25(_uploadFile, _downloadFile, value.transactionType),
        coinSymbol: value.coinSymbol,
        pricePerCoin: value.pricePerCoin,
        notes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        coinName: value.coinName,
        coinId: value.coinId,
        amount: value.amount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    direction: {
        above: null;
    } | {
        below: null;
    };
    createdAt: bigint;
    targetPrice: number;
    coinName: string;
    coinId: string;
    triggered: boolean;
}): {
    id: string;
    direction: Variant_above_below;
    createdAt: bigint;
    targetPrice: number;
    coinName: string;
    coinId: string;
    triggered: boolean;
} {
    return {
        id: value.id,
        direction: from_candid_variant_n31(_uploadFile, _downloadFile, value.direction),
        createdAt: value.createdAt,
        targetPrice: value.targetPrice,
        coinName: value.coinName,
        coinId: value.coinId,
        triggered: value.triggered
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    coinSymbol: string;
    coinQuantity: number;
    orderType: _OrderType;
    priceAtExecution: number;
    timestamp: bigint;
    fiatAmount: number;
    stripePaymentIntentId: [] | [string];
    coinId: string;
}): {
    id: string;
    status: OrderStatus;
    coinSymbol: string;
    coinQuantity: number;
    orderType: OrderType;
    priceAtExecution: number;
    timestamp: bigint;
    fiatAmount: number;
    stripePaymentIntentId?: string;
    coinId: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n35(_uploadFile, _downloadFile, value.status),
        coinSymbol: value.coinSymbol,
        coinQuantity: value.coinQuantity,
        orderType: from_candid_OrderType_n37(_uploadFile, _downloadFile, value.orderType),
        priceAtExecution: value.priceAtExecution,
        timestamp: value.timestamp,
        fiatAmount: value.fiatAmount,
        stripePaymentIntentId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.stripePaymentIntentId)),
        coinId: value.coinId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    username: string;
    displayName: string;
    createdAt: _Timestamp;
    settings: [] | [_UserSettings];
    profilePictureUrl: [] | [string];
}): {
    id: UserId;
    username: string;
    displayName: string;
    createdAt: Timestamp;
    settings?: UserSettings;
    profilePictureUrl?: string;
} {
    return {
        id: value.id,
        username: value.username,
        displayName: value.displayName,
        createdAt: value.createdAt,
        settings: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.settings)),
        profilePictureUrl: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.profilePictureUrl))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ChartData;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ChartData;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ChartData_n12(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    line: null;
} | {
    candle: null;
}): ChartKind {
    return "line" in value ? ChartKind.line : "candle" in value ? ChartKind.candle : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_NewsItem>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<NewsItem>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GlobalResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GlobalResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MarketResponse;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MarketResponse;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): OrderType {
    return "buy" in value ? OrderType.buy : "sell" in value ? OrderType.sell : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    above: null;
} | {
    below: null;
}): Variant_above_below {
    return "above" in value ? Variant_above_below.above : "below" in value ? Variant_above_below.below : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "failed" in value ? OrderStatus.failed : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PriceAlert>): Array<PriceAlert> {
    return value.map((x)=>from_candid_PriceAlert_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeOrder>): Array<TradeOrder> {
    return value.map((x)=>from_candid_TradeOrder_n33(_uploadFile, _downloadFile, x));
}
function to_candid_ChartKind_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartKind): _ChartKind {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PriceAlert_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceAlert): _PriceAlert {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileInput_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileInput): _ProfileInput {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_TradeOrder_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeOrder): _TradeOrder {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionInput_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionInput): _TransactionInput {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: OrderStatus;
    coinSymbol: string;
    coinQuantity: number;
    orderType: OrderType;
    priceAtExecution: number;
    timestamp: bigint;
    fiatAmount: number;
    stripePaymentIntentId?: string;
    coinId: string;
}): {
    id: string;
    status: _OrderStatus;
    coinSymbol: string;
    coinQuantity: number;
    orderType: _OrderType;
    priceAtExecution: number;
    timestamp: bigint;
    fiatAmount: number;
    stripePaymentIntentId: [] | [string];
    coinId: string;
} {
    return {
        id: value.id,
        status: to_candid_OrderStatus_n3(_uploadFile, _downloadFile, value.status),
        coinSymbol: value.coinSymbol,
        coinQuantity: value.coinQuantity,
        orderType: to_candid_OrderType_n5(_uploadFile, _downloadFile, value.orderType),
        priceAtExecution: value.priceAtExecution,
        timestamp: value.timestamp,
        fiatAmount: value.fiatAmount,
        stripePaymentIntentId: value.stripePaymentIntentId ? candid_some(value.stripePaymentIntentId) : candid_none(),
        coinId: value.coinId
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionType: TransactionType;
    coinSymbol: string;
    pricePerCoin: number;
    notes?: string;
    timestamp: Timestamp;
    coinName: string;
    coinId: string;
    amount: number;
}): {
    id: string;
    transactionType: _TransactionType;
    coinSymbol: string;
    pricePerCoin: number;
    notes: [] | [string];
    timestamp: _Timestamp;
    coinName: string;
    coinId: string;
    amount: number;
} {
    return {
        id: value.id,
        transactionType: to_candid_TransactionType_n45(_uploadFile, _downloadFile, value.transactionType),
        coinSymbol: value.coinSymbol,
        pricePerCoin: value.pricePerCoin,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        timestamp: value.timestamp,
        coinName: value.coinName,
        coinId: value.coinId,
        amount: value.amount
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    direction: Variant_above_below;
    createdAt: bigint;
    targetPrice: number;
    coinName: string;
    coinId: string;
    triggered: boolean;
}): {
    id: string;
    direction: {
        above: null;
    } | {
        below: null;
    };
    createdAt: bigint;
    targetPrice: number;
    coinName: string;
    coinId: string;
    triggered: boolean;
} {
    return {
        id: value.id,
        direction: to_candid_variant_n48(_uploadFile, _downloadFile, value.direction),
        createdAt: value.createdAt,
        targetPrice: value.targetPrice,
        coinName: value.coinName,
        coinId: value.coinId,
        triggered: value.triggered
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    profilePictureUrl?: string;
}): {
    username: string;
    displayName: string;
    profilePictureUrl: [] | [string];
} {
    return {
        username: value.username,
        displayName: value.displayName,
        profilePictureUrl: value.profilePictureUrl ? candid_some(value.profilePictureUrl) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_above_below): {
    above: null;
} | {
    below: null;
} {
    return value == Variant_above_below.above ? {
        above: null
    } : value == Variant_above_below.below ? {
        below: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    buy: null;
} | {
    sell: null;
} {
    return value == OrderType.buy ? {
        buy: null
    } : value == OrderType.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChartKind): {
    line: null;
} | {
    candle: null;
} {
    return value == ChartKind.line ? {
        line: null
    } : value == ChartKind.candle ? {
        candle: null
    } : value;
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TransactionInput>): Array<_TransactionInput> {
    return value.map((x)=>to_candid_TransactionInput_n43(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
